# Generated by Django 5.0.3 on 2024-03-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_photo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
